### ISSUE TITLE
Duty git plugin

### ISSUE THREAD

**Issue by JanOwiesniak** [JanOwiesniak/duty#30]
I have implemented a few useful git commands to show what it could look like.

Please take a look at [duty](https://github.com/JanOwiesniak/duty) [README](https://github.com/JanOwiesniak/duty/blob/master/README.md) and [duty-git](https://github.com/JanOwiesniak/duty-git) [README](https://github.com/JanOwiesniak/duty-git/blob/master/README.md) and let me know what you think about the approach.

/cc @rrrene @jnbt

**Comment by JanOwiesniak** [comment]
I'm not satisfied with the solution how other plugins e.g [duty-git](https://github.com/JanOwiesniak/duty-git/blob/master/lib/duty/git.rb) [integrate with duty](https://github.com/JanOwiesniak/duty/blob/master/lib/duty/plugins.rb#L45).

/cc @splattael @holderbaum

**Comment by jnbt** [comment]
It feels a little bit like re-implementing parts of bundler / rubygems here. But I assume you don't want to rely on bundler as a dependency.

If it would be possible to also load "plugins" only by adding them to the Gemfile this would also solve the problem how to install the plugins (local source, rubygems.org, git).

Perhaps the easiest way to solve this would be to "inverse" the registration mechanism as this would allow to register plugins only by loading them via Bundler. Also the interface would be more explicit than to return the Plugin module as in https://github.com/JanOwiesniak/duty-git/blob/master/lib/duty/git.rb#L110. So instead of eval(...) just call something like `Duty::Plugins.register(...)` at the end of `duty/git.rb`.

Or: At the current state you require to inherit from `::Duty::Tasks::Base` to be a valid "plugin"-task. So you could just keep the possibility to require plugins by ".duty.yml", but only rely on this inheritance for discovery?

In any case I would try to allow installing plugins by just being load by "any" source (`.duty.yml`,  `Gemfile` or just a per-project `require`-statement)

**Comment by rrrene** [comment]
I've already expressed my concern with implementing a micro-service-architecture (a.k.a. da plugin system) before we have a working prototype (a monolith, if you will). We could have avoided [three weeks of bikeshedding](https://en.wiktionary.org/wiki/bikeshedding) this way.

IMHO @jnbt is right: it is always better to let Plugins register themselves. It is explicit, clean and allows the code to be loaded in any way the user wants. Coincidentally, it's also [how Texas let's view helpers register themselves](https://github.com/rrrene/texas/blob/e157dda2b870b9a902b9a1bdf72a253418469053/spec/fixtures/lib-helpers/lib/helpers/document_helper.rb#L7).

**Comment by JanOwiesniak** [comment]
@jnbt 

I will try to integrate it with bundler and try out the `Duty::Plugins.register(...)`  approach. Thanks for the advise!

@rrrene 

You are probably right that i concentrate too early, too much on the details.
I still liked my architectural approach and as long as the core utility is tested well enough through an integration test everything should be ok.

**Comment by JanOwiesniak** [comment]
The plugin registers it self and the gem stuff is working too.
